# Generated by Django 2.0.5 on 2018-05-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_topiccategory_topic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video_id', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('topic_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TopicCategory')),
            ],
        ),
    ]
