# Generated by Django 2.0.5 on 2018-05-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_topiccontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiccontent',
            old_name='topic_category_id',
            new_name='topic_category',
        ),
    ]
