# Generated by Django 2.0.5 on 2018-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180506_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccontent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
