# Generated by Django 2.0.5 on 2018-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_topiccontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
