# Generated by Django 2.0.5 on 2018-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180506_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccontent',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
