# Generated by Django 2.0.5 on 2018-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180506_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccontent',
            name='order',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
