# Generated by Django 2.0.5 on 2018-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180508_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccontent',
            name='order',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
