# Generated by Django 2.0.5 on 2018-05-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_siteoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccategory',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
